cafe/BrewHaven/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    # path('', views.CoffeeList.as_view(), name = "home"),
    path('coffee/<int:pk>', views.ProdDetails.as_view(), name="coffee_details" ),
    path('search/', views.search_view, name='search')
]

cafe/authentication/urls.py
from django.urls import path
from .views import UserRegisterView
# from .views import register_page, login_page,logOut,search_result

urlpatterns = [
   # path('register/', register_page, name = "register"),
    path('signup/',UserRegisterView.as_view(), name='register'),
   # path('logOut/', logOut, name="logOut")
  

]

cafe/cafe/urls.py
# from .views import register_page, login_page
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('BrewHaven.urls')),
    path('admin/', admin.site.urls),
    path('authentication/',include('authentication.urls')),
     path('authentication/', include('django.contrib.auth.urls')),
    # path('register/',register_page, name='register'),
    path('cart/',include ('cart.urls')),
    # path('search/',include('search.urls')),
    ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cafe/cart/urls.py
from django.urls import path
from .views import view_cart
from . import views 


app_name = "cart"

urlpatterns = [
    path('cartpage/',view_cart, name = "cartpage"),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]
    
    

cafe/BrewHaven/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Coffee(models.Model):
     name = models.CharField(max_length = 255)
     price = models.FloatField()
     quantity = models.IntegerField()
     img = models.ImageField(upload_to="coffees/", null=True)

#class CartItem(models.Model):
     #cartuser = models.ForeignKey(User, on_delete=models.CASCADE)
    # quantity = models.IntegerField()
     #item = models.ForeignKey(Coffee, on_delete=models.CASCADE)
     #total_price = models.FloatField()
     

cafe/authentication/models.py
from django.db import models

# Create your models here.

cafe/cart/models.py
from django.db import models
from BrewHaven.models import Coffee
from django.contrib.auth.models import User




# Create your models here



#class Cart(models.Model):
    #cart_id = models.CharField(max_length=255, blank=True)
    #coffee = models.ForeignKey(Coffee, on_delete=models.CASCADE)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    #quantity = models.IntegerField(default=1)
    #totalprice = models.FloatField(default=0.0)
    #timestamp =  models.DateTimeField(auto_now_add = True)

    #class Meta:
       # db_table = 'cart'

class CartItem(models.Model):
    Coffee= models.ForeignKey(Coffee, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return f'{self.quantity} x {self.Coffee.name}'

    
    

cafe/authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length = 20)
    last_name = forms.CharField(max_length = 20)
    email = forms.EmailField()
    password2 =forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password', 'password2','email']
   
    

cafe/BrewHaven/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader # helps load the template
from .models import Coffee

from django.views.generic import ListView, DetailView




# Create your views here.
def home(request):
    template = loader.get_template('home.html')
    coffees = Coffee.objects.all()
    context = {
        'coffee1': coffees
    }
    return HttpResponse(template.render(context, request))

def register(request):
    return HttpResponse("Hi this is a registeration page....!")
      

# class CoffeeList(ListView):
#     queryset = Coffee.objects.all()
#     template_name = "home.html"

    

class ProdDetails(DetailView):
    queryset = Coffee.objects.all()
    template_name = 'prod_details.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProdDetails, self).get_context_data(*args, **kwargs)
        return context 
    

def search_view(request):
    query=request.GET.get('q')
    results= Coffee.objects.filter(name__icontains=query)
    template='search_result.html'
    context={
        'results':results,
        'query':query
    }
    return render(request,template,context)
    
    
    
    

cafe/authentication/views.py
from django.shortcuts import redirect, render
from .forms import UserRegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views import generic 







# Create your views here.

def register_page(request):
    form = UserRegisterForm()
    context ={
        "title" : "register Page",
        "form"  : form
    }
    
    if request.method=='POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=True)
            user.set_password(user.password)
            user.save()
            return redirect('/login')
        else:
            return render(request,"register.html",context)
    return render(request,"register.html",context)


class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')
        

                      
                      

cafe/cart/views.py
from django.shortcuts import render,redirect
from .models import Coffee, CartItem





# Create your views here.
#def cart_home(request):
    #request.session['cart_id'] = 1
    #request.session['user'] = request.user.username
    #context = {

    #}
    #template = "cart/home.html"
   # return render(request, template, context)


def view_cart(request):
    template = "cart\cart.html"
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    return render(request, template, {'cart_items': cart_items, 'total_price': total_price})
 
def add_to_cart(request, product_id):
    Coffee = Coffee.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(Coffee=Coffee, 
                                                       user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart:view_cart')
 
def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('cart:view_cart')

    

    

cafe/BrewHaven/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{% static '/css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

      {% if user.is_authenticated %}
        <a class="navbar-brand" href="#">Welcome {{ user.username }}</a>
      {% else %}
        <a class="navbar-brand" href="#">Welcome to the shop !!! </a>
      {% endif %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            <!-- Section ends here -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
            </li>

            </ul>
            <!-- <form class="d-flex" method="get" action="{% url 'search' %}">
        
              <input name = 'q' class="form-control me-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->

   
             

          {% else %}
          <li class="nav-item">
            <button class="btn btn-primary" href="{% url 'cart:cartpage' %}">Cart</button>
          </li>
          
          <li class="nav-item">
            <form method="post" action="{% url 'logout' %}">
              {%csrf_token %}
              <button class ="btn btn-secondary" type="submit">Logout</button>
             
          </form>
          </li>
          {% endif %}
          

          </ul>
          
          
          <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'search' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name = 'q'>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>


    {% block content %}
    {% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/ffeb2cbf9b.js" crossorigin="anonymous"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

cafe/BrewHaven/templates/header.html
<div class="nav-item drop">
    <a href="#" class="nav-link dropdown-toggle bg-primary text-white"data-bs-tog
    <div class="dropdown-menu m-0">
        <a href="{% url 'login' %}" class="dropdown-item">Login</a>
        <a href="#" class="dropdown-item">Logout</a>
        <a href="#" class="dropdown-item">order History</a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'register' %}"class="dropdown-item">sign up</a>
    </div>
</div>

cafe/BrewHaven/templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container d-flex justify-content-center mt-50 mb-50">
    <div class="row">

        
    {% for c in coffee1 %}
        <div class="col-md-3 mt-2">
            <div class="card bg-light hover">
                <div class="card-body">
                    <a href="{% url 'coffee_details' c.pk %}">
                    <div class="card-image">
                        <img src="{{ c.img }}" width="100px" height="100px" >
                    </div>
                    <div>
                        
                            {{ c.name }} (${{c.price}})
                    </div>
                </a>
                </div>
            </div>
            
        </div>
    {% endfor %}
    </div>
</div>   



{% endblock %}

cafe/BrewHaven/templates/prod_details.html
{% extends 'base.html' %}

{% block title %}
{{ coffee.name }}
{% endblock %}


{% block content %}


<section class="py-5">
    <div class="container">
      <div class="row gx-5">
        <aside class="col-lg-6">
          <div class=" rounded-4 mb-3 d-flex justify-content-center">
            <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="/{{ coffee.img }}">
              <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="/{{ coffee.img }}" />
            </a>
          </div>

          <!-- thumbs-wrap.// -->
          <!-- gallery-wrap .end// -->
        </aside>
        
        <main class="col-lg-6">
          <div class="ps-lg-3">
            <h4 class="title text-dark">
                {{coffee.name}}
            </h4>
            <div class="d-flex flex-row my-3">
              <div class="text-warning mb-1 me-2">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
                <span class="ms-1">
                  4.5
                </span>
              </div>
              <span class="text-muted"><i class="fas fa-shopping-basket fa-sm mx-1"></i>154 orders</span>
              <span class="text-success ms-2">In stock</span>
            </div>
  
            <div class="mb-3">
              <span class="h5">&#8377; {{coffee.price}}</span>
              <span class="text-muted">/per order</span>
            </div>
  
            <p>
              Some paragraph
            </p>
  
            <div class="row">
              <dt class="col-3">Type:</dt>
              <dd class="col-9">Regular</dd>
  
              <dt class="col-3">Color</dt>
              <dd class="col-9">Brown</dd>
  
              
            </div>
  
            <hr />
  
            <div class="row mb-4">
              <div class="col-md-4 col-6">
                <label class="mb-2">Size</label>
                <select class="form-select border border-secondary" style="height: 35px;">
                  <option>Small</option>
                  <option>Medium</option>
                  <option>Large</option>
                </select>
              </div>
              <!-- col.// -->
              <div class="col-md-4 col-6 mb-3">
                <label class="mb-2 d-block">Quantity</label>
                <div class="input-group mb-3" style="width: 170px;">
                  <button class="btn btn-white border border-secondary px-3" type="button" id="button-addon1" data-mdb-ripple-color="dark">
                    <i class="fas fa-minus"></i>
                  </button>
                  <input id = "q_value" type="number" class="form-control text-center border border-secondary" value="0" aria-label="Example text with button addon" aria-describedby="button-addon1" />
                  <button class="btn btn-white border border-secondary px-3" type="button" id="button-addon2" data-mdb-ripple-color="dark">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
              </div>
            </div>
            <a href="#" class="btn btn-warning shadow-0"> Buy now </a>
            <a href="#" class="btn btn-primary shadow-0"> <i class="me-1 fa fa-shopping-basket"></i> Add to cart </a>
            <a href="#" class="btn btn-light border border-secondary py-2 icon-hover px-3"> <i class="me-1 fa fa-heart fa-lg"></i> Save </a>
          </div>
        </main>
      </div>
    </div>
  </section>

{% endblock %}

cafe/BrewHaven/templates/search_result.html
{% extends 'base.html' %}

{% block content %}
<h1>Search Result for "{{ query }}"</h1>

<ul>
    <div class="container-fluid">
        {% for c in results %}
        <br>
        <a href ="{% url 'coffee_details' c.pk %}">
            <div class="row hover">
                <div class="col-xs-6 col-md-4">
                    <img src="/{{ c.img }}" alt = "coffee pic"  width="200" height="150"> 
                    
                </div>
                <div class="col-xs-12 col-md-8">
                    {{c.name}}
                    <br>
                    {{c.price}} rupees
                </div>
            </div>
        </a>
        {% empty %}

        <p>No results found.</p>

        {% endfor %}
    </div>


</ul>

{% endblock %}

cafe/authentication/templates/register.html
{% extends 'base.html' %}
{% block title %} {% endblock %}

{% block content %}

<div class="mx-auto">

<form align='center' method="POST">
    {% csrf_token %}

    {{form.as_p}}
    <input type="submit" value="sign up"/>
</form>
</div>
{% endblock %}

cafe/cart/templates/cart.html
<!-- cart/cart.html -->

<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		/* Add CSS styles for flex container and items */
		.product-list {
			display: flex;
			flex-wrap: wrap; /* Allow items to wrap to the next row if necessary */
			justify-content: space-between; /* Space items evenly along the main axis */
			list-style: none; /* Remove list styles */
			padding: 0;
		}

		.product-item {
			
			flex: 1; /* Grow to fill available space evenly */
			/* Limit item width to avoid overcrowding */
			margin: 10px; /* Add spacing between items */
			border: 1px solid #ccc; /* Add a border for visual separation */
			padding: 10px;
			text-align: center;
		}

		/* Style the "Buy Now" button */
		.buy-now-button {
			display: block;
			margin-top: 10px;
			background-color: #007bff;
			color: #fff;
			text-decoration: none;
			padding: 5px 10px;
			border-radius: 5px;
		}
	</style>
</head>

<body>

	<h1>Your Shopping Cart</h1>

	<div class="product-list">

	

	{% for item in cart_items %}
	<div class="product-item">
		<p>{{ item.product.name }} ({{ item.quantity }})</p>
		<p>Price: ${{ item.product.price }}</p>
		<a href="{% url 'cart:remove_from_cart' item.id %}">Remove</a>
	</div>
	{% empty %}
	<p>Your cart is empty.</p>
	{% endfor %}

	</div>

	<p>Total Price: ${{ total_price }}</p>

	<a href="{% url 'BrewHaven' %}">Continue Shopping</a>

</body>

</html>

cafe/cart/templates/home.html
{% extends 'base.html' %}


{% block title %}
{{ title }}
{% endblock %}


{% block content %}
{{ content }}
This is the cart




<script>
    $(document).ready(function() {
        $('.qnt').change(function() {
            quantity = $(this).val()
            price = $(this).parent().prev().html()
            id = $(this).attr('cartid')

            $.ajax({
                url: "cart/updatecart/",
                method: POST,
                data: { 
                    'qnt' : quantity, 
                    'price': price,
                    'cid' : id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'

                },
                success : function (response) {
                    $("#totalprice" + id).val(response.totalprice);
                    $("#totalamount").val(response.totalam);  
                },
                error:  function() {

                }
            })
        })
    })
</script>
{% endblock %}